

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword

ngrok:
    image: wernight/ngrok
    restart: always
    depends_on:
      - wordpress
    command: ["ngrok", "http", "--log=stdout", "wordpress:80"]
    environment:
      NGROK_AUTHTOKEN: 2wC10LrII2YGPOEV9ojAxiBmEqh_7uwcMQuWnX1c5AaBirdba # Get from ngrok dashboard
    ports:
      - "4040:4040"

volumes:
  wordpress_data:
  db_data:
